### ISSUE TITLE
mermaid tag enabled error

### ISSUE THREAD

**Issue by qzi** [theme-next/theme-next.org#85]
```
# Mermaid tag 
mermaid:
  enable: true
  # Available themes: default | dark | forest | neutral
  theme: forest
```

hexo g 渲染失败，所有的页面都无法渲染

`ERROR Cannot read property 'replace' of null`
